var BC={};BC.Math=function(){return{radians:function(a){return a*Math.PI/180}}}();BC.Time=function(){return{getTimeInSeconds:function(){return 0.001*Date.now()}}}();function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function subtractVectors(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]]}function normalize(a){var b=Math.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2]);return 1E-5<b?[a[0]/b,a[1]/b,a[2]/b]:[0,0,0]};function makeLookAt(a,b,c){b=normalize(subtractVectors(a,b));c=cross(c,b);var e=cross(b,c);return[c[0],c[1],c[2],0,e[0],e[1],e[2],0,b[0],b[1],b[2],0,a[0],a[1],a[2],1]}function makePerspective(a,b,c,e){a=Math.tan(0.5*Math.PI-0.5*a);var f=1/(c-e);return[a/b,0,0,0,0,a,0,0,0,0,(c+e)*f,-1,0,0,c*e*f*2,0]}function makeTranslation(a,b,c){return[1,0,0,0,0,1,0,0,0,0,1,0,a,b,c,1]}function makeXRotation(a){var b=Math.cos(a);a=Math.sin(a);return[1,0,0,0,0,b,a,0,0,-a,b,0,0,0,0,1]}
function makeYRotation(a){var b=Math.cos(a);a=Math.sin(a);return[b,0,-a,0,0,1,0,0,a,0,b,0,0,0,0,1]}function makeZRotation(a){var b=Math.cos(a);a=Math.sin(a);return[b,a,0,0,-a,b,0,0,0,0,1,0,0,0,0,1]}function makeScale(a,b,c){return[a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1]}
function makeInverse(a){var b=a[0],c=a[1],e=a[2],f=a[3],g=a[4],d=a[5],l=a[6],m=a[7],n=a[8],p=a[9],r=a[10],h=a[11],q=a[12],k=a[13],s=a[14];a=a[15];var v=r*a,w=s*h,u=l*a,t=s*m,x=l*h,y=r*m,z=e*a,A=s*f,B=e*h,C=r*f,D=e*m,E=l*f,F=n*k,G=q*p,H=g*k,I=q*d,J=g*p,K=n*d,L=b*k,M=q*c,N=b*p,O=n*c,P=b*d,Q=g*c,R=v*d+t*p+x*k-(w*d+u*p+y*k),S=w*c+z*p+C*k-(v*c+A*p+B*k),k=u*c+A*d+D*k-(t*c+z*d+E*k),c=y*c+B*d+E*p-(x*c+C*d+D*p),d=1/(b*R+g*S+n*k+q*c);return[d*R,d*S,d*k,d*c,d*(w*g+u*n+y*q-(v*g+t*n+x*q)),d*(v*b+A*n+B*q-(w*b+
z*n+C*q)),d*(t*b+z*g+E*q-(u*b+A*g+D*q)),d*(x*b+C*g+D*n-(y*b+B*g+E*n)),d*(F*m+I*h+J*a-(G*m+H*h+K*a)),d*(G*f+L*h+O*a-(F*f+M*h+N*a)),d*(H*f+M*m+P*a-(I*f+L*m+Q*a)),d*(K*f+N*m+Q*h-(J*f+O*m+P*h)),d*(H*r+K*s+G*l-(J*s+F*l+I*r)),d*(N*s+F*e+M*r-(L*r+O*s+G*e)),d*(L*l+Q*s+I*e-(P*s+H*e+M*l)),d*(P*r+J*e+O*l-(N*l+Q*r+K*e))]}
function matrixMultiply(a,b){return[a[0]*b[0]+a[1]*b[4]+a[2]*b[8]+a[3]*b[12],a[0]*b[1]+a[1]*b[5]+a[2]*b[9]+a[3]*b[13],a[0]*b[2]+a[1]*b[6]+a[2]*b[10]+a[3]*b[14],a[0]*b[3]+a[1]*b[7]+a[2]*b[11]+a[3]*b[15],a[4]*b[0]+a[5]*b[4]+a[6]*b[8]+a[7]*b[12],a[4]*b[1]+a[5]*b[5]+a[6]*b[9]+a[7]*b[13],a[4]*b[2]+a[5]*b[6]+a[6]*b[10]+a[7]*b[14],a[4]*b[3]+a[5]*b[7]+a[6]*b[11]+a[7]*b[15],a[8]*b[0]+a[9]*b[4]+a[10]*b[8]+a[11]*b[12],a[8]*b[1]+a[9]*b[5]+a[10]*b[9]+a[11]*b[13],a[8]*b[2]+a[9]*b[6]+a[10]*b[10]+a[11]*b[14],a[8]*
b[3]+a[9]*b[7]+a[10]*b[11]+a[11]*b[15],a[12]*b[0]+a[13]*b[4]+a[14]*b[8]+a[15]*b[12],a[12]*b[1]+a[13]*b[5]+a[14]*b[9]+a[15]*b[13],a[12]*b[2]+a[13]*b[6]+a[14]*b[10]+a[15]*b[14],a[12]*b[3]+a[13]*b[7]+a[14]*b[11]+a[15]*b[15]]};var error=function(a){window.console&&(window.console.error?window.console.error(a):window.console.log&&window.console.log(a))},loadShader=function(a,b,c,e){e=e||error;c=a.createShader(c);a.shaderSource(c,b);a.compileShader(c);return a.getShaderParameter(c,a.COMPILE_STATUS)?c:(lastError=a.getShaderInfoLog(c),e("*** Error compiling shader '"+c+"':"+lastError),a.deleteShader(c),null)},createProgram=function(a,b,c,e){for(var f=a.createProgram(),g=0;g<b.length;g++)a.attachShader(f,b[g]);if(c)for(g=0;g<
c.length;g++)a.bindAttribLocation(f,e?e[g]:g,c[g]);a.linkProgram(f);return a.getProgramParameter(f,a.LINK_STATUS)?f:(lastError=a.getProgramInfoLog(f),error("Error in program linking: "+lastError),a.deleteProgram(f),null)};
$(document).ready(function(){function a(){function a(){var b=BC.Time.getTimeInSeconds(),d=b-p;p=b;h[1]+=r*d;var e=makeZRotation(h[2]),b=makeYRotation(h[1]),d=makeXRotation(h[0]),e=matrixMultiply(q,e),e=matrixMultiply(e,b),e=matrixMultiply(e,d),e=matrixMultiply(e,k),e=matrixMultiply(e,s),e=matrixMultiply(e,w),b=c.createBuffer();c.bindBuffer(c.ARRAY_BUFFER,b);c.bufferData(c.ARRAY_BUFFER,new Float32Array([-1,1,1,-1,-1,1,1,-1,1,-1,1,1,1,-1,1,1,1,1,1,1,1,1,-1,1,1,-1,-1,1,1,1,1,-1,-1,1,1,-1,-1,1,1,1,1,
-1,-1,1,-1,-1,1,1,1,1,1,1,1,-1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,1,-1,-1,-1,1,1,-1,-1,-1,-1,-1,1,-1,1,1,-1,1,-1,-1,-1,-1]),c.STATIC_DRAW);c.enableVertexAttribArray(l);c.vertexAttribPointer(l,3,c.FLOAT,!1,0,0);c.uniformMatrix4fv(n,!1,e);b=c.createBuffer();c.bindBuffer(c.ARRAY_BUFFER,b);c.enableVertexAttribArray(m);c.vertexAttribPointer(m,2,c.FLOAT,!1,0,0);c.bufferData(c.ARRAY_BUFFER,new Float32Array([0,0,0,1,1,1,0,0,1,1,1,0,0,0,0,1,1,1,0,0,1,1,1,0,0,1,1,0,0,0,0,1,1,1,1,0,1,0,0,1,1,1,1,0,0,0,
0,1,1,0,0,1,1,1,1,0,0,0,0,1]),c.STATIC_DRAW);c.clear(c.COLOR_BUFFER_BIT|c.DEPTH_BUFFER_BIT);c.drawArrays(c.TRIANGLES,0,30);requestAnimationFrame(a)}var d=createProgram(c,[e,f]);c.useProgram(d);var l=c.getAttribLocation(d,"a_position"),m=c.getAttribLocation(d,"a_texcoord"),n=c.getUniformLocation(d,"u_matrix"),p=BC.Time.getTimeInSeconds(),r=1,h=[BC.Math.radians(0),BC.Math.radians(0),BC.Math.radians(0)],d=[1,1,1],q=makeScale(d[0],d[1],d[2]),d=[0,0,0],k=makeTranslation(d[0],d[1],d[2]),d=makeLookAt([3,
3,3],[0,0,0],[0,1,0]),s=makeInverse(d),d=b.width/b.height,v=BC.Math.radians(55),w=makePerspective(v,d,1,2E3),u=c.createTexture();c.bindTexture(c.TEXTURE_2D,u);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,1,1,0,c.RGBA,c.UNSIGNED_BYTE,new Uint8Array([0,0,255,255]));var t=new Image;t.src="images/texture.png";t.addEventListener("load",function(){c.bindTexture(c.TEXTURE_2D,u);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,t);c.generateMipmap(c.TEXTURE_2D)});a()}var b=document.getElementById("canvas"),
c=b.getContext("webgl")||b.getContext("experimental-webgl");if(c){c.enable(c.CULL_FACE);c.enable(c.DEPTH_TEST);var e,f;$.when($.get("/shaders/vertex.glsl",function(a){e=loadShader(c,a,c.VERTEX_SHADER)}),$.get("/shaders/fragment.glsl",function(a){f=loadShader(c,a,c.FRAGMENT_SHADER)})).then(a)}});
