application: blockcillin
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/css

- url: /glsl
  static_dir: static/glsl

- url: /js
  static_dir: static/js

- url: /.*
  script: _go_app
