application: blockcillin
version: 1
runtime: go
api_version: go1

handlers:
- url: /audio
  static_dir: res/audio

- url: /css
  static_dir: res/css

- url: /docs
  static_dir: res/docs

- url: /favicon.ico
  static_files: res/images/favicon.png
  upload: res/images/favicon.png

- url: /images
  static_dir: res/images

- url: /js
  static_dir: res/js

- url: /third_party
  static_dir: res/third_party

- url: /.*
  script: _go_app
