application: blockcillin
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: res/css

- url: /images
  static_dir: res/images

- url: /js
  static_dir: res/js

- url: /jscompiled
  static_dir: res/jscompiled

- url: /jstests
  static_dir: res/jstests

- url: /shaders
  static_dir: res/shaders

- url: /.*
  script: _go_app
