application: blockcillin
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: res/css

- url: /images
  static_dir: res/images

- url: /js
  static_dir: res/js

- url: /.*
  script: _go_app
